DROP TABLE APP_USER;

CREATE TABLE APP_USER (
ID NUMBER(10,0) NOT NULL AUTO_INCREMENT,
FIRST_NAME VARCHAR2(255) DEFAULT NULL,
LAST_NAME VARCHAR2(255) DEFAULT NULL,
BIRTH_DATE VARCHAR2(255) DEFAULT NULL,
PHONE_NUMBER VARCHAR2(255) DEFAULT NULL,
EMAIL_ID VARCHAR2(255) DEFAULT NULL,
PRIMARY KEY (ID));

DROP SEQUENCE hibernate_sequence;

CREATE SEQUENCE hibernate_sequence;
